S4597925Assign2/Models/ErrorViewModel.cs
using System;

namespace S4597925Assign2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

S4597925Assign2/ViewModels/LoginViewModel.cs
using Octokit;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace S4597925Assign2.ViewModels
{
    // Login viewModel for user login
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me")]
        public bool RememberMe { get; set; }
    }
}

S4597925Assign2/Controllers/AttendeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using S4597925Assign2.Data.Interface;
using S4597925Assign2.Data.Model;
using S4597925Assign2.Data.Repository;

namespace S4597925Assign2.Controllers
{
    // Controller page for the attendee model 
    public class AttendeeController : Controller
    {
        private readonly IAttendeeRepository _attendeeRepository;

        public AttendeeController(IAttendeeRepository attendeeRepository)
        {
            _attendeeRepository = attendeeRepository;
        }

        public ViewResult Index()
        {
            var model = _attendeeRepository.GetAllAttendee();
            return View(model);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Attendee attendees)
        {
            if(!ModelState.IsValid)
            {
                return View(attendees);
            }
            _attendeeRepository.Add(attendees);
            return RedirectToAction("Index");
        }


        /**
        public IActionResult Update(Attendee attendee)
        {
            if(!ModelState.IsValid)
            {
                return View(attendee);
            }
            _attendeeRepository.Update(Attendee);
            return RedirectToAction("Index");
        }
        **/
    }
}

S4597925Assign2/Controllers/ConferenceController.cs
using System;
using S4597925Assign2.Data.Interface;
using S4597925Assign2.Data.Model;
using S4597925Assign2.Data.Repository;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace S4597925Assign2.Controllers
{
    // Controller class for the conference model 
    public class ConferenceController : Controller
    {
        private readonly IConferenceRepository _conferenceRepository;

        public ConferenceController(IConferenceRepository conferenceRepository)
        {
            _conferenceRepository = conferenceRepository;
        }

        // Displays Conference Details
        public ViewResult Index()
        {
            var model = _conferenceRepository.GetAllConference();
            return View(model);
        }
    }
}

S4597925Assign2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using S4597925Assign2.Models;

namespace S4597925Assign2.Controllers
{
    // Home controller - Displays the Main page and the contact page
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

S4597925Assign2/Controllers/OrganizerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using S4597925Assign2.Data.Interfaces;
using S4597925Assign2.Data.Model;
using S4597925Assign2.Data.Repository;

namespace S4597925Assign2.Controllers
{
    // Controller class for organizer model
    public class OrganizerController : Controller
    {
        private readonly IOrganizerRepository _organizerRepository;

        public OrganizerController(IOrganizerRepository organizerRepository)
        {
            _organizerRepository = organizerRepository;
        }

        public ViewResult Index()
        {
            var model = _organizerRepository.GetAllOrganizer();
            return View(model);
        }

        // Customizing my own error message 
        // Error message alerts user when invalid organizer ID is entered in the URL
        public ViewResult Details(int? id)
        {
            // Customizing Error Message
            Organizer organizer = _organizerRepository.GetOrganizer(id.Value);
            if (organizer == null)
            {
                Response.StatusCode = 404;
                return View("OrganizerNotFound", id.Value);

            }
            OrganizerRepository organizerDetail = new OrganizerRepository()
            {
                Organizer = _organizerRepository.GetOrganizer(id ?? 1),
                PageTitle = "Organizer Detail"
            };

            return View(organizerDetail);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Organizer organizer)
        {
            if (ModelState.IsValid)
            {
                Organizer newOrganizer = _organizerRepository.Add(organizer);
                return RedirectToAction("details", new { id = newOrganizer.Id });
            }
            return View();
        }
    }
}

S4597925Assign2/Views/Attendee/Create.cshtml
@model S4597925Assign2.Data.Model.Attendee

@{
    ViewBag.Title = "Create Attendee";
}

<form asp-controller="Organizer" asp-action="Create" method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Name" class="form-control" placeholder="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control" placeholder="Email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="ConferenceName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="ConferenceName" class="custom-select mr-sm-2"
                    asp-items="Html.GetEnumSelectList<S4597925Assign2.Data.Model.ConferenceTitles>()">
                <option value="">Please Select</option>
            </select>
            <span asp-validation-for="ConferenceName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="btn-group col-md-offset-2 col-md-6">
            <input class="btn btn-default" type="submit" value="Return" asp-controller="Attendee" asp-action="Empty" />
            <input class="btn btn-success" type="submit" value="Register" />
        </div>
    </div>
</form>

S4597925Assign2/Views/Attendee/Empty.cshtml
<a class="btn btn-success mt-5" style="margin: 10px" asp-controller="Customer" asp-action="Create">Register New Attendee</a>

<h2>No Attendees.</h2>

S4597925Assign2/Views/Attendee/Index.cshtml
@model IEnumerable<S4597925Assign2.Data.Model.Attendee>

@{ 
    ViewBag.Title = "List of Attendees";
}

    <div class="text-center" , style="background-color: lightslategray;">
        <h1 class="display-4" , style="color:white;">Attendees</h1>
    </div>

    <a class="btn btn-success mt-5" style="margin: 10px" asp-controller="Attendee" asp-action="Create">Register New Attendee</a>
    
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Conference</th>
                <th>Edit Attendee</th>
                <th>Delete Attendee</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var attendee in Model)
            {
                <tr>
                    <td>@attendee.ID</td>
                    <td>@attendee.Name</td>
                    <td>@attendee.Email</td>
                    <td>@attendee.ConferenceName</td>
                    <td><a class="btn btn-info" asp-area="" asp-controller="Attendee" asp-action="Update" asp-route-id="@attendee.ID">Edit</a></td>
                    <td><a class="btn btn-danger" asp-area="" asp-controller="Attendee" asp-action="Delete" asp-route-id="@attendee.ID">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>

S4597925Assign2/Views/Attendee/Update.cshtml
@model S4597925Assign2.Data.Model.Attendee

<div class="row orderForm">
    <form asp-controller="Author" asp-action="Update" method="post" class="form-horizontal" role="form">
        <h3 class="col-md-offset-2">Edit Author @Model.Name</h3>
        @Html.HiddenFor(m => Model.ID)
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="btn-group col-md-offset-2 col-md-6">
                <input class="btn btn-default" type="submit" value="Return" asp-controller="Attendee" asp-action="Index" />
                <input class="btn btn-success" type="submit" value="Update" />
            </div>
        </div>
    </form>
</div>

S4597925Assign2/Views/Conference/Index.cshtml
@model IEnumerable<S4597925Assign2.Data.Model.Conference>
@{
    ViewData["Title"] = "Conference Page";
}

    <div class="text-center" , style="background-color: lightslategray;">
        <h1 class="display-4" , style="color:white;">Conferences</h1>
    </div>

    <div style="overflow-x:auto">
        <table style="width:100%">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Code</th>
                    <th>Title</th>
                    <th>Location</th>
                    <th>Organizer</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var conference in Model)
                {
                    <tr>
                        <td>@conference.Id</td>
                        <td>@conference.Date</td>
                        <td>@conference.Code</td>
                        <td>@conference.Title</td>
                        <td>@conference.Location</td>
                        <td>@Html.ActionLink((conference.OrganizerName), "details", "organizer", new { id = (@conference.OrganizerID) })</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

S4597925Assign2/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Page";
}

<body>
    <div class="text-center" , style="background-color: lightslategray;">
        <h1 class="display-4" , style="color:white;">Contact Us</h1>
    </div>


    <h4>
        Student's Contact Details:
    </h4>
    <dl>
        <dt>Mobile Number:</dt>
        <dd>+61 478 524 198</dd>
        <dt>Email Address:</dt>
        <dd>laxmi.gurung2@live.vu.edu.au</dd>
    </dl>
</body>

S4597925Assign2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <body>
        <div class="text-center" , style="background-color: lightslategray;">
            <h1 class="display-4" , style="color:white;">Conference Management System</h1>
        </div>

        <h4>This Web Application is developed by:</h4>
        <dl>
            <dt>Student Name:</dt>
            <dd>Laxmi Gurung</dd>
            <dt>Student ID:</dt>
            <dd>s4597925</dd>
            <dt>Unit:</dt>
            <dd>NIT3112 Advanced Web Application Development (Assignment 2)</dd>
            <dt>Location:</dt>
            <dd>Victory University Sydney</dd>
            <dt>Due Date:</dt>
            <dd>14/June/2020 (11.59pm)</dd>
        </dl>
    </body>

S4597925Assign2/Views/Organizer/Create.cshtml
@model S4597925Assign2.Data.Model.Organizer
@inject S4597925Assign2.Data.Repository.IOrganizerRepository _orgRepository

@{
    ViewBag.Title = "Create Attendee";
}

<form asp-controller="Organizer" asp-action="Create" method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Name" class="form-control" placeholder="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control" placeholder="Email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="ConferenceName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="ConferenceName" class="custom-select mr-sm-2"
                    asp-items="Html.GetEnumSelectList<S4597925Assign2.Data.Model.ConferenceTitles>()"></select>
        </div>
    </div>
    <div class="form-group row">
        <div class="btn-group col-md-offset-2 col-md-6">
            <input class="btn btn-default" type="submit" value="Return" asp-controller="Organizer" asp-action="Index" />
            <input class="btn btn-success" type="submit" value="Register"/>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            Number of Organizers = @_orgRepository.GetAllOrganizer().Count()
        </div>
    </div>
</form>

S4597925Assign2/Views/Organizer/Details.cshtml
@model S4597925Assign2.Data.Interfaces.OrganizerRepository
<html>
<head>
    <title></title>
</head>
<body>
    <div class="text-center" , style="background-color: lightslategray;">
        <h1 class="display-4" , style="color:white;">Organizer's Details</h1>
    </div>
    <a class="btn btn-success mt-5" style="margin: 10px" asp-controller="Organizer" asp-action="Create">Add New Organizer</a>
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header text-center">
                <h1>@Model.Organizer.Name</h1>
            </div>

            <div class="card-body text-center">
                <h4>Organizer's ID: @Model.Organizer.Id</h4>
                <h4>Email: @Model.Organizer.Email</h4>
                <h4>Conference: @Model.Organizer.ConferenceName.</h4>

            </div>

            <div class="card-footer text-center">
                <a href="/Organizer/index" class="btn btn-primary">List of Organizers</a>

            </div>
        </div>
    </div>


</body>
</html>

S4597925Assign2/Views/Organizer/Index.cshtml
@{
    ViewBag.Title = "Organizer List";
}
    <div class="text-center" , style="background-color: lightslategray;">
        <h1 class="display-4" , style="color:white;">Organizers</h1>
    </div>
    <a class="btn btn-success mt-5" style="margin: 10px" asp-controller="Organizer" asp-action="Create">Add New Organizers</a>
<div class="card-deck">
    @foreach (var organizer in Model)
    {
        <div class="card m-3">
            <div class="card-header text-center">
                <img src="~/Images/individual.png" />
                <h3>@organizer.Name</h3>
            </div>
            <div class="card-footer text-center">
                <a href="/Organizer/Details/@organizer.Id" class="btn btn-primary">View</a>
            </div>
        </div>
    }
</div>

S4597925Assign2/Views/Organizer/OrganizerNotFound.cshtml
@model int  

@{ 
    ViewBag.Title = "404 Error";
}

<div class="alert alert-danger mt-1 mb-1">
    <h4>404 Not Found Error :</h4>
    <hr />
    <h5> Organizer with ID = @Model cannot be found</h5>
</div>
<a asp-action="index" asp-controller="organizer" class="btn btn-outline-success">
    Click here to see the list of all organizers.
</a>

S4597925Assign2/Views/Organizer/Update.cshtml
@model S4597925Assign2.Data.Model.Organizer

<div class="row orderForm">
    <form asp-controller="Organizer" asp-action="Update" method="post" class="form-horizontal" role="form">
        <h3 class="col-md-offset-2">Edit Author @Model.Name</h3>
        @Html.HiddenFor(m => Model.Id)
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="btn-group col-md-offset-2 col-md-6">
                <input class="btn btn-default" type="submit" value="Return" asp-controller="Organizer" asp-action="List" />
                <input class="btn btn-success" type="submit" value="Update" />
            </div>
        </div>
    </form>
</div>

S4597925Assign2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - S4597925Assign2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="http://apta.asia/">
                    <img src="~/Images/logo.png" height="100" width="100" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Conference" asp-action="Index">Conferences</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Attendee" asp-action="Index">Attendees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Organizer" asp-action="Index">Organizers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Conference - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>